- README.md
- backend/Habit tracker API.postman_collection.json
- backend/habit-tracker-database.sql
- backend/index.js
- habit-tracker-app/src/App.css
- habit-tracker-app/src/App.jsx
- habit-tracker-app/src/hobbies/hobbiesApp.css
- habit-tracker-app/src/hobbies/hobbiesApp.jsx
- habit-tracker-app/src/medication/medicationApp.css
- habit-tracker-app/src/medication/medicationApp.jsx
- habit-tracker-app/src/movement/movementApp.css
- habit-tracker-app/src/movement/movementApp.jsx
- habit-tracker-app/src/nutrition/nutritionApp.css
- habit-tracker-app/src/nutrition/nutritionApp.jsx
- habit-tracker-app/src/reading/readingApp.css
- habit-tracker-app/src/reading/readingApp.jsx
- habit-tracker-app/src/sleep/sleepApp.css
- habit-tracker-app/src/sleep/sleepApp.jsx
README.md file updated with project document information which is required as part of the final project submission
Details regarding user testing and conclusion to be completed before project submission deadline
Nutrition habit tracking component added to React app
Movement habit tracking component added to React app
Reading habit tracking component added to React app
Sleep habit tracking component added to React app
Medication habit tracking component added to React app
Hobbies habit tracking component added to React app
API and temporary database updated to demonstrate functionality of habit tracking components
> React/CSS and README.md files updated

- habit-tracker-app/src/App.jsx
- habit-tracker-app/src/login/login.css
- habit-tracker-app/src/login/login.jsx
- habit-tracker-app/src/login/register.jsx
Adding basic template of login and register pages to combine with tailwind
> basic login and register template

- habit-tracker-app/src/App.jsx
- habit-tracker-app/src/assets/styles/bottomnavigation.css
- habit-tracker-app/src/components/BottomNavigation.jsx
Ignore the branch name - forgot to change it :(
> adding bottom navigation

- backend/package-lock.json
- backend/package.json
Last PR/merge included a change to the backend package.json file which meant that the correct dependencies were not being installed - it looks like part of the code was removed from the package.json file was removed in error
File repaired
> Package json file repair

- habit-tracker-app/src/App.jsx
- habit-tracker-app/src/assets/styles/habitIcon.css
- habit-tracker-app/src/assets/styles/habitSquare.css
- habit-tracker-app/src/components/Grid.jsx
- habit-tracker-app/src/components/HabitIcon.jsx
- habit-tracker-app/src/components/HabitSquare.jsx
- habit-tracker-app/src/components/problemQuestion.js
- habit-tracker-app/src/hobbies/hobbiesApp.css
- habit-tracker-app/src/hobbies/hobbiesApp.jsx
- habit-tracker-app/src/hydration/hydrationApp.jsx
- habit-tracker-app/src/medication/medicationApp.jsx
- habit-tracker-app/src/movement/movementApp.jsx
- habit-tracker-app/src/nutrition/nutritionApp.jsx
- habit-tracker-app/src/reading/readingApp.jsx
- habit-tracker-app/src/sleep/sleepApp.jsx
Icons added to all components but styling is required. Also removed rogue punctuation marks.
> Add icons to components

- habit-tracker-app/src/App.jsx
- habit-tracker-app/src/components/Navigation.jsx
- habit-tracker-app/src/login/login.jsx
- habit-tracker-app/src/login/register.jsx
- habit-tracker-app/src/pages/habit-tracker.jsx
- Amended app.jsx to include routing
- Created a page for habit tracker
- Amended the login/register components to allow routing
> adding routing

- habit-tracker-app/package-lock.json
- habit-tracker-app/package.json
- habit-tracker-app/src/App.css
- habit-tracker-app/src/assets/styles/habitComponents.css
- habit-tracker-app/src/assets/styles/habitIcon.css
- habit-tracker-app/src/assets/styles/habitSquare.css
- habit-tracker-app/src/components/HabitSquare.jsx
- habit-tracker-app/src/hobbies/hobbiesApp.css
- habit-tracker-app/src/hobbies/hobbiesApp.jsx
- habit-tracker-app/src/hydration/hydrationApp.css
- habit-tracker-app/src/hydration/hydrationApp.jsx
- habit-tracker-app/src/medication/medicationApp.css
- habit-tracker-app/src/medication/medicationApp.jsx
- habit-tracker-app/src/movement/movementApp.css
- habit-tracker-app/src/movement/movementApp.jsx
- habit-tracker-app/src/nutrition/nutritionApp.css
- habit-tracker-app/src/nutrition/nutritionApp.jsx
- habit-tracker-app/src/reading/readingApp.css
- habit-tracker-app/src/reading/readingApp.jsx
- habit-tracker-app/src/sleep/sleepApp.css
- habit-tracker-app/src/sleep/sleepApp.jsx
- habit-tracker-app/tailwind.config.js
Colours added to each habit component and change on hover. Need help rotating the text and icon for the hydration component.
> Styling components

- habit-tracker-app/src/components/HabitSquare.jsx
Hopefully, fixed the 'onClick is not a function' error.
> fixed the 'onClick is not a function error

- habit-tracker-app/src/pages/habit-tracker.jsx
> Further error correction

- habit-tracker-app/src/App.jsx
- habit-tracker-app/src/assets/styles/bottomnavigation.css
- habit-tracker-app/src/components/BottomNavigation.jsx
- habit-tracker-app/src/components/Navigation.jsx
- changed the bottom nav to match the top nav styling
- fixed the nav to the top of the page
- added padding to the app component to ensure the navbars don't overlap content
> editing top and bottom nav styling

- habit-tracker-app/src/calendarviews/calendarviewsApp.css
- habit-tracker-app/src/calendarviews/calendarviewsApp.jsx
- habit-tracker-app/src/pages/habit-tracker.jsx
Habit tracker API updated with GET function to display completion data from database
Data will be integrated/displayed on React/CSS page based on design/wireframe
> Habit tracker API updated, database info displayed on React app

- habit-tracker-app/package-lock.json
- habit-tracker-app/package.json
- habit-tracker-app/src/pages/habit-tracker.jsx
- habit-tracker-app/src/socialmediasharingAPI/socialmediasharingAPI.css
- habit-tracker-app/src/socialmediasharingAPI/socialmediasharingAPI.jsx
Added links to share app/progress on social media
> Social media sharing links added

- habit-tracker-app/src/App.css
- habit-tracker-app/src/components/BottomNavigation.jsx
- habit-tracker-app/src/components/HabitApp.jsx
- habit-tracker-app/src/components/HydrationApp2.jsx
- habit-tracker-app/src/components/Navigation.jsx
- habit-tracker-app/src/index.css
- habit-tracker-app/src/login/login.jsx
- habit-tracker-app/src/login/register.jsx
- habit-tracker-app/src/pages/habit-tracker.jsx
- Have made an attempt at refactoring the habit app components - just 1 example of 'hydration app 2' in there atm. Let me know what you think!
> Adding tailwind to components

- README.md
- backend/User registration-login API.postman_collection.json
- backend/config/db.js
- backend/config/dotenv.js
- backend/controllers/authController.js
- backend/habit-tracker-db.sql
- backend/index.js
- backend/middlewares/userValidation.js
- backend/models/Users.js
- backend/server.js
- habit-tracker-app/src/login/login.jsx
- habit-tracker-app/src/login/register.jsx
Code reviewed and amended to confirm user login/registration API is working
API will have to run on port 3002 to avoid conflicts with React app and habit tracker API
Amendments made to code to match with final SQL database
Index.js file amended to account for type/module being integrated into package.JSON
Path updated for location of dotenv file
Login page seems to be working
Code on register.jsx file needs reviewing - not functioning as expected
> Updating user login/registration API

- habit-tracker-app/src/App.jsx
- habit-tracker-app/src/components/ViewDaily.jsx
- habit-tracker-app/src/components/ViewMonthly.jsx
- habit-tracker-app/src/components/ViewWeekly.jsx
- habit-tracker-app/src/components/ViewYearly.jsx
- habit-tracker-app/src/pages/HabitViews.jsx
- created habit view main page
- created dropdown for which view the user chooses
- render the view on the habitview page using useEffect
- components created for daily, weekly, monthly, yearly habit views
> creating habit view page

- habit-tracker-app/src/components/HabitTable.jsx
- Still looks a mess on small screens but I am knackered!
> Weekly page

- habit-tracker-app/src/calendarviews/calendarviewsApp.jsx
- habit-tracker-app/src/pages/about-us.jsx
About page updated
Error corrected on calendarviewsApp.jsx file - correct date was not being shown, this has been fixed now
> Habit tracker api updates

- backend/index.js
- backend/server.js
- backend/wordOftheDayAPI.js
- habit-tracker-app/package.json
With Kenny's help, I've merged the three backend files into index.js. Server.js and the Word of the day file are still there but commented out incase we have any issues. Meg, please check your auth is still working correctly as I don't know how it works.
Thanks
> three backend files merged into one - index.js

- habit-tracker-app/src/components/HabitTable.jsx
Improvements to styling on med and large screens but made it worse on mobile!
> View styling

- backend/User registration-login API.postman_collection.json
- backend/index.js
- backend/server.js
- habit-tracker-app/src/login/login.jsx
- habit-tracker-app/src/login/register.jsx
changing the port numbers from 3002 to 3001 to merge with the backend changes from earlier today
> changing port numbers for login & register

- habit-tracker-app/src/App.css
- habit-tracker-app/src/App.jsx
- habit-tracker-app/src/assets/styles/custom.css
- habit-tracker-app/tailwind.config.js
We have circles! I also understand how to move them around! They look fairly similar to the mock-up but I can move them if needed!
> colourful cirles added to background of the app

- backend/middlewares/userValidation.js
- habit-tracker-app/src/login/login.jsx
- habit-tracker-app/src/login/register.jsx
CSS changed on text to allow red text only to show if error
> Changes to confirm password field

- package-lock.json
- package.json
No need for two terminals to run separately for the app to run
After setting up the .env file - user follows the instructions below:
cd Group-7-project
Enter in the terminal: npm start
> Only one terminal needed to run app

- README.md
- backend/config/dotenvexample.js
- backend/index.js
Example .env file updated - in example file and README.md
> Updates to repo and backend

- habit-tracker-app/src/pages/habit-tracker.jsx
- habit-tracker-app/src/socialmedia/socialmediaApp.jsx
Tidied up habits page
Still haven't been able to only display the habits being tracked, will try later
> Backend updates 3

- habit-tracker-app/src/components/BottomNavigation.jsx
- habit-tracker-app/src/components/Navigation.jsx
Added goal setting button to bottom nav for mobile users
Changed the profile link on bottom nav to calendar view links as profile data not populating (can add back in quickly if need to)
Updated both nav bars to remove duplicate options
Bottom nav bar now only appears in mobile view with burger menu for logout and settings options
> Nav updates
